substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: mp-ai-video-clipping-web
  _REPO_NAME: mp-ai-video
  _API_BASE_URL: https://mp-ai-video-clipping-api-CHANGE_ME.a.run.app
  _IMAGE_TAG: latest
  _GCS_BUCKET_NAME: mp-ai-video-clipping-bucket-v2

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${_IMAGE_TAG}
      - --build-arg
      - NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL}
      - --build-arg
      - NEXT_PUBLIC_GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}
      - apps/web
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${_IMAGE_TAG}
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${_IMAGE_TAG}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=1Gi
      - --cpu=1
      - --set-env-vars=NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL},NEXT_PUBLIC_GCS_BUCKET_NAME=${_GCS_BUCKET_NAME}

images:
  - ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/web:${_IMAGE_TAG}
