{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.className }}
  namespace: {{ .Values.namespace }}
spec:
  provider: gcp
  parameters:
    secrets: |
{{- range .Values.secretProvider.secrets }}
      - resourceName: "projects/{{ $.Values.gcp.projectId }}/secrets/{{ .name }}/versions/{{ .version }}"
        path: "{{ .name }}"
{{- end }}
{{- end }}

