apiVersion: v1
kind: ServiceAccount
metadata:
  name: mpstudio
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mpstudio.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccountEmail | quote }}

