/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/prima-theme.ts
 * Command: astryx theme build lib/prima-theme.ts
 * Generated: 2026-07-09T15:16:29.467Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const primaTheme: DefinedTheme;
